### ISSUE TITLE
Need Admin On-Page Notification of Disconnection from Eloqua with Timestamp

### ISSUE THREAD

**Issue by rubicon** [solepixel/gravityforms-eloqua#8] opened 2016-04-06 21:12 UTC
Authentication to Eloqua can disconnect periodically.  When this occurs the only notification is the email that is sent.  Would it also be possible to add a Admin-wide disconnect banner message at the top and on the Eloqua settings page in GF show a notification as well, with timestamp.  It would be greatly appreciated.

**Comment by rubicon** [comment] 2016-04-20 13:37
Any thoughts

**Comment by solepixel** [comment] 2016-04-29 05:37
@rubicon Hey I added an admin notification (with the ability to disable it). I wasn't able to get the timestamp in this version, but I should be able to add that in next time I'm able to work on this. Please download the latest version and let me know if you see any issues with it.

**Comment by rubicon** [comment] 2016-08-12 17:22
Thanks for doing that.  It seems to work but it does mess up the css/layout of the GF settings area pretty badly when it is activated.  Are you using this to implement it? 

https://codex.wordpress.org/Plugin_API/Action_Reference/admin_notices.

 It would definitely need to be a notice that shows at the top of every page (not just the GF area) so we can be sure to know.  I believe that's the way to do it, but could be wrong.  Here's a screenshot.

![screenshot-2016-08-12-12 16 24a](https://cloud.githubusercontent.com/assets/98216/17630912/3910f1f4-6087-11e6-98ac-f9f917d1f4f9.jpg)

**Comment by solepixel** [comment] 2016-08-19 01:34
@rubicon Try the latest version (1.5.1) to see if this is resolved.

**Comment by solepixel** [comment] 2016-12-11 22:30
I'm going to close this issue assuming the issue is resolved. If you're still having problems with the latest version related to this issue, please feel free to re-open and add details. Thanks!

**Closed as completed by solepixel** 2016-12-11 22:30 UTC
Labels: enhancement
